/*This object containing both native and formal languages was put together by the creator of this plugin, with the languages and their ISO codes sourced from https://www.localeplanet.com/icu*/

var describrLangs = {
    "af-formal": "Afrikaans",
    "af_NA-formal": "Afrikaans (Namibia)",
    "af_NA-native": "Afrikaans (Namibië)",
    "af_ZA-formal": "Afrikaans (South Africa)",
    "af_ZA-native": "Afrikaans (Suid-Afrika)",
    "agq-formal": "Aghem",
    "agq_CM-formal": "Aghem (Cameroon)",
    "agq_CM-native": "Aghem (Kàmàlûŋ)",
    "ak-formal": "Akan",
    "ak_GH-formal": "Akan (Ghana)",
    "ak_GH-native": "Akan (Gaana)",
    "am-formal": "Amharic",
    "am-native": "አማርኛ",
    "am_ET-formal": "Amharic (Ethiopia)",
    "am_ET-native": "አማርኛ (ኢትዮጵያ)",
    "ar-formal": "Arabic",
    "ar-native": "العربية",
    "ar_001-formal": "Arabic (World)",
    "ar_001-native": "العربية (العالم)",
    "ar_AE-formal": "Arabic (United Arab Emirates)",
    "ar_AE-native": "العربية (الإمارات العربية المتحدة)",
    "ar_BH-formal": "Arabic (Bahrain)",
    "ar_BH-native": "العربية (البحرين)",
    "ar_DJ-formal": "Arabic (Djibouti)",
    "ar_DJ-native": "العربية (جيبوتي)",
    "ar_DZ-formal": "Arabic (Algeria)",
    "ar_DZ-native": "العربية (الجزائر)",
    "ar_EG-formal": "Arabic (Egypt)",
    "ar_EG-native": "العربية (مصر)",
    "ar_EH-formal": "Arabic (Western Sahara)",
    "ar_EH-native": "العربية (الصحراء الغربية)",
    "ar_ER-formal": "Arabic (Eritrea)",
    "ar_ER-native": "العربية (إريتريا)",
    "ar_IL-formal": "Arabic (Israel)",
    "ar_IL-native": "العربية (إسرائيل)",
    "ar_IQ-formal": "Arabic (Iraq)",
    "ar_IQ-native": "العربية (العراق)",
    "ar_JO-formal": "Arabic (Jordan)",
    "ar_JO-native": "العربية (الأردن)",
    "ar_KM-formal": "Arabic (Comoros)",
    "ar_KM-native": "العربية (جزر القمر)",
    "ar_KW-formal": "Arabic (Kuwait)",
    "ar_KW-native": "العربية (الكويت)",
    "ar_LB-formal": "Arabic (Lebanon)",
    "ar_LB-native": "العربية (لبنان)",
    "ar_LY-formal": "Arabic (Libya)",
    "ar_LY-native": "العربية (ليبيا)",
    "ar_MA-formal": "Arabic (Morocco)",
    "ar_MA-native": "العربية (المغرب)",
    "ar_MR-formal": "Arabic (Mauritania)",
    "ar_MR-native": "العربية (موريتانيا)",
    "ar_OM-formal": "Arabic (Oman)",
    "ar_OM-native": "العربية (عُمان)",
    "ar_PS-formal": "Arabic (Palestinian Territories)",
    "ar_PS-native": "العربية (الأراضي الفلسطينية)",
    "ar_QA-formal": "Arabic (Qatar)",
    "ar_QA-native": "العربية (قطر)",
    "ar_SA-formal": "Arabic (Saudi Arabia)",
    "ar_SA-native": "العربية (المملكة العربية السعودية)",
    "ar_SD-formal": "Arabic (Sudan)",
    "ar_SD-native": "العربية (السودان)",
    "ar_SO-formal": "Arabic (Somalia)",
    "ar_SO-native": "العربية (الصومال)",
    "ar_SS-formal": "Arabic (South Sudan)",
    "ar_SS-native": "العربية (جنوب السودان)",
    "ar_SY-formal": "Arabic (Syria)",
    "ar_SY-native": "العربية (سوريا)",
    "ar_TD-formal": "Arabic (Chad)",
    "ar_TD-native": "العربية (تشاد)",
    "ar_TN-formal": "Arabic (Tunisia)",
    "ar_TN-native": "العربية (تونس)",
    "ar_YE-formal": "Arabic (Yemen)",
    "ar_YE-native": "العربية (اليمن)",
    "as-formal": "Assamese",
    "as-native": "অসমীয়া",
    "as_IN-formal": "Assamese (India)",
    "as_IN-native": "অসমীয়া (ভারত)",
    "asa-formal": "Asu",
    "asa-native": "Kipare",
    "asa_TZ-formal": "Asu (Tanzania)",
    "asa_TZ-native": "Kipare (Tadhania)",
    "ast-formal": "Asturian",
    "ast-native": "asturianu",
    "ast_ES-formal": "Asturian (Spain)",
    "ast_ES-native": "asturianu (España)",
    "az-formal": "Azerbaijani",
    "az-native": "azərbaycan",
    "az_Cyrl-formal": "Azerbaijani (Cyrillic)",
    "az_Cyrl-native": "азәрбајҹан (Кирил)",
    "az_Cyrl_AZ-formal": "Azerbaijani (Cyrillic, Azerbaijan)",
    "az_Cyrl_AZ-native": "азәрбајҹан (Кирил, Азәрбајҹан)",
    "az_Latn-formal": "Azerbaijani (Latin)",
    "az_Latn-native": "azərbaycan (latın)",
    "az_Latn_AZ-formal": "Azerbaijani (Latin, Azerbaijan)",
    "az_Latn_AZ-native": "azərbaycan (latın, Azərbaycan)",
    "bas-formal": "Basaa",
    "bas-native": "Ɓàsàa",
    "bas_CM-formal": "Basaa (Cameroon)",
    "bas_CM-native": "Ɓàsàa (Kàmɛ̀rûn)",
    "be-formal": "Belarusian",
    "be-native": "беларуская",
    "be_BY-formal": "Belarusian (Belarus)",
    "be_BY-native": "беларуская (Беларусь)",
    "bem-formal": "Bemba",
    "bem-native": "Ichibemba",
    "bem_ZM-formal": "Bemba (Zambia)",
    "bem_ZM-native": "Ichibemba (Zambia)",
    "bez-formal": "Bena",
    "bez-native": "Hibena",
    "bez_TZ-formal": "Bena (Tanzania)",
    "bez_TZ-native": "Hibena (Hutanzania)",
    "bg-formal": "Bulgarian",
    "bg-native": "български",
    "bg_BG-formal": "Bulgarian (Bulgaria)",
    "bg_BG-native": "български (България)",
    "bm-formal": "Bambara",
    "bm-native": "bamanakan",
    "bm_ML-formal": "Bambara (Mali)",
    "bm_ML-native": "bamanakan (Mali)",
    "bn-formal": "Bangla",
    "bn-native": "বাংলা",
    "bn_BD-formal": "Bangla (Bangladesh)",
    "bn_BD-native": "বাংলা (বাংলাদেশ)",
    "bn_IN-formal": "Bangla (India)",
    "bn_IN-native": "বাংলা (ভারত)",
    "bo-formal": "Tibetan",
    "bo-native": "བོད་སྐད་",
    "bo_CN-formal": "Tibetan (China)",
    "bo_CN-native": "བོད་སྐད་ (རྒྱ་ནག)",
    "bo_IN-formal": "Tibetan (India)",
    "bo_IN-native": "བོད་སྐད་ (རྒྱ་གར་)",
    "br-formal": "Breton",
    "br-native": "brezhoneg",
    "br_FR-formal": "Breton (France)",
    "br_FR-native": "brezhoneg (Frañs)",
    "brx-formal": "Bodo",
    "brx-native": "बड़ो",
    "brx_IN-formal": "Bodo (India)",
    "brx_IN-native": "बड़ो (भारत)",
    "bs-formal": "Bosnian",
    "bs-native": "bosanski",
    "bs_Cyrl-formal": "Bosnian (Cyrillic)",
    "bs_Cyrl-native": "босански (ћирилица)",
    "bs_Cyrl_BA-formal": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
    "bs_Cyrl_BA-native": "босански (ћирилица, Босна и Херцеговина)",
    "bs_Latn-formal": "Bosnian (Latin)",
    "bs_Latn-native": "bosanski (latinica)",
    "bs_Latn_BA-formal": "Bosnian (Latin, Bosnia & Herzegovina)",
    "bs_Latn_BA-native": "bosanski (latinica, Bosna i Hercegovina)",
    "ca-formal": "Catalan",
    "ca-native": "català",
    "ca_AD-formal": "Catalan (Andorra)",
    "ca_AD-native": "català (Andorra)",
    "ca_ES-formal": "Catalan (Spain)",
    "ca_ES-native": "català (Espanya)",
    "ca_FR-formal": "Catalan (France)",
    "ca_FR-native": "català (França)",
    "ca_IT-formal": "Catalan (Italy)",
    "ca_IT-native": "català (Itàlia)",
    "ccp-formal": "Chakma",
    "ccp-native": "𑄌𑄋𑄴𑄟𑄳𑄦",
    "ccp_BD-formal": "Chakma (Bangladesh)",
    "ccp_BD-native": "𑄌𑄋𑄴𑄟𑄳𑄦 (𑄝𑄁𑄣𑄘𑄬𑄌𑄴)",
    "ccp_IN-formal": "Chakma (India)",
    "ccp_IN-native": "𑄌𑄋𑄴𑄟𑄳𑄦 (𑄞𑄢𑄧𑄖𑄴)",
    "ce-formal": "Chechen",
    "ce-native": "нохчийн",
    "ce_RU-formal": "Chechen (Russia)",
    "ce_RU-native": "нохчийн (Росси)",
    "cgg-formal": "Chiga",
    "cgg-native": "Rukiga",
    "cgg_UG-formal": "Chiga (Uganda)",
    "cgg_UG-native": "Rukiga (Uganda)",
    "chr-formal": "Cherokee",
    "chr-native": "ᏣᎳᎩ",
    "chr_US-formal": "Cherokee (United States)",
    "chr_US-native": "ᏣᎳᎩ (ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᏍᎦᏚᎩ)",
    "ckb-formal": "Central Kurdish",
    "ckb-native": "کوردیی ناوەندی",
    "ckb_IQ-formal": "Central Kurdish (Iraq)",
    "ckb_IQ-native": "کوردیی ناوەندی (عێراق)",
    "ckb_IR-formal": "Central Kurdish (Iran)",
    "ckb_IR-native": "کوردیی ناوەندی (ئێران)",
    "cs-formal": "Czech",
    "cs-native": "čeština",
    "cs_CZ-formal": "Czech (Czechia)",
    "cs_CZ-native": "čeština (Česko)",
    "cy-formal": "Welsh",
    "cy-native": "Cymraeg",
    "cy_GB-formal": "Welsh (United Kingdom)",
    "cy_GB-native": "Cymraeg (Y Deyrnas Unedig)",
    "da-formal": "Danish",
    "da-native": "dansk",
    "da_DK-formal": "Danish (Denmark)",
    "da_DK-native": "dansk (Danmark)",
    "da_GL-formal": "Danish (Greenland)",
    "da_GL-native": "dansk (Grønland)",
    "dav-formal": "Taita",
    "dav-native": "Kitaita",
    "dav_KE-formal": "Taita (Kenya)",
    "dav_KE-native": "Kitaita (Kenya)",
    "de-formal": "German",
    "de-native": "Deutsch",
    "de_AT-formal": "German (Austria)",
    "de_AT-native": "Deutsch (Österreich)",
    "de_BE-formal": "German (Belgium)",
    "de_BE-native": "Deutsch (Belgien)",
    "de_CH-formal": "German (Switzerland)",
    "de_CH-native": "Deutsch (Schweiz)",
    "de_DE-formal": "German (Germany)",
    "de_DE-native": "Deutsch (Deutschland)",
    "de_IT-formal": "German (Italy)",
    "de_IT-native": "Deutsch (Italien)",
    "de_LI-formal": "German (Liechtenstein)",
    "de_LI-native": "Deutsch (Liechtenstein)",
    "de_LU-formal": "German (Luxembourg)",
    "de_LU-native": "Deutsch (Luxemburg)",
    "dje-formal": "Zarma",
    "dje-native": "Zarmaciine",
    "dje_NE-formal": "Zarma (Niger)",
    "dje_NE-native": "Zarmaciine (Nižer)",
    "dsb-formal": "Lower Sorbian",
    "dsb-native": "dolnoserbšćina",
    "dsb_DE-formal": "Lower Sorbian (Germany)",
    "dsb_DE-native": "dolnoserbšćina (Nimska)",
    "dua-formal": "Duala",
    "dua-native": "duálá",
    "dua_CM-formal": "Duala (Cameroon)",
    "dua_CM-native": "duálá (Cameroun)",
    "dyo-formal": "Jola-Fonyi",
    "dyo-native": "joola",
    "dyo_SN-formal": "Jola-Fonyi (Senegal)",
    "dyo_SN-native": "joola (Senegal)",
    "dz-formal": "Dzongkha",
    "dz-native": "རྫོང་ཁ",
    "dz_BT-formal": "Dzongkha (Bhutan)",
    "dz_BT-native": "རྫོང་ཁ། (འབྲུག།)",
    "ebu-formal": "Embu",
    "ebu-native": "Kĩembu",
    "ebu_KE-formal": "Embu (Kenya)",
    "ebu_KE-native": "Kĩembu (Kenya)",
    "ee-formal": "Ewe",
    "ee-native": "Eʋegbe",
    "ee_GH-formal": "Ewe (Ghana)",
    "ee_GH-native": "Eʋegbe (Ghana nutome)",
    "ee_TG-formal": "Ewe (Togo)",
    "ee_TG-native": "Eʋegbe (Togo nutome)",
    "el-formal": "Greek",
    "el-native": "Ελληνικά",
    "el_CY-formal": "Greek (Cyprus)",
    "el_CY-native": "Ελληνικά (Κύπρος)",
    "el_GR-formal": "Greek (Greece)",
    "el_GR-native": "Ελληνικά (Ελλάδα)",
    "en_UK-formal": "English (United Kingdom)",
    "en_UK-native": "English (UK)",
    "en_US-formal": "English (United States)",
    "en_US-native": "English (US)",
    "eo-formal": "Esperanto",
    "eo-native": "esperanto",
    "es-formal": "Spanish",
    "es-native": "español",
    "es_419-formal": "Spanish (Latin America)",
    "es_419-native": "español (Latinoamérica)",
    "es_AR-formal": "Spanish (Argentina)",
    "es_AR-native": "español (Argentina)",
    "es_BO-formal": "Spanish (Bolivia)",
    "es_BO-native": "español (Bolivia)",
    "es_BR-formal": "Spanish (Brazil)",
    "es_BR-native": "español (Brasil)",
    "es_BZ-formal": "Spanish (Belize)",
    "es_BZ-native": "español (Belice)",
    "es_CL-formal": "Spanish (Chile)",
    "es_CL-native": "español (Chile)",
    "es_CO-formal": "Spanish (Colombia)",
    "es_CO-native": "español (Colombia)",
    "es_CR-formal": "Spanish (Costa Rica)",
    "es_CR-native": "español (Costa Rica)",
    "es_CU-formal": "Spanish (Cuba)",
    "es_CU-native": "español (Cuba)",
    "es_DO-formal": "Spanish (Dominican Republic)",
    "es_DO-native": "español (República Dominicana)",
    "es_EA-formal": "Spanish (Ceuta & Melilla)",
    "es_EA-native": "español (Ceuta y Melilla)",
    "es_EC-formal": "Spanish (Ecuador)",
    "es_EC-native": "español (Ecuador)",
    "es_ES-formal": "Spanish (Spain)",
    "es_ES-native": "español (España)",
    "es_GQ-formal": "Spanish (Equatorial Guinea)",
    "es_GQ-native": "español (Guinea Ecuatorial)",
    "es_GT-formal": "Spanish (Guatemala)",
    "es_GT-native": "español (Guatemala)",
    "es_HN-formal": "Spanish (Honduras)",
    "es_HN-native": "español (Honduras)",
    "es_IC-formal": "Spanish (Canary Islands)",
    "es_IC-native": "español (Canarias)",
    "es_MX-formal": "Spanish (Mexico)",
    "es_MX-native": "español (México)",
    "es_NI-formal": "Spanish (Nicaragua)",
    "es_NI-native": "español (Nicaragua)",
    "es_PA-formal": "Spanish (Panama)",
    "es_PA-native": "español (Panamá)",
    "es_PE-formal": "Spanish (Peru)",
    "es_PE-native": "español (Perú)",
    "es_PH-formal": "Spanish (Philippines)",
    "es_PH-native": "español (Filipinas)",
    "es_PR-formal": "Spanish (Puerto Rico)",
    "es_PR-native": "español (Puerto Rico)",
    "es_PY-formal": "Spanish (Paraguay)",
    "es_PY-native": "español (Paraguay)",
    "es_SV-formal": "Spanish (El Salvador)",
    "es_SV-native": "español (El Salvador)",
    "es_US-formal": "Spanish (United States)",
    "es_US-native": "español (Estados Unidos)",
    "es_UY-formal": "Spanish (Uruguay)",
    "es_UY-native": "español (Uruguay)",
    "es_VE-formal": "Spanish (Venezuela)",
    "es_VE-native": "español (Venezuela)",
    "et-formal": "Estonian",
    "et-native": "eesti",
    "et_EE-formal": "Estonian (Estonia)",
    "et_EE-native": "eesti (Eesti)",
    "eu-formal": "Basque",
    "eu-native": "euskara",
    "eu_ES-formal": "Basque (Spain)",
    "eu_ES-native": "euskara (Espainia)",
    "ewo-formal": "Ewondo",
    "ewo-native": "ewondo",
    "ewo_CM-formal": "Ewondo (Cameroon)",
    "ewo_CM-native": "ewondo (Kamərún)",
    "fa-formal": "Persian",
    "fa-native": "فارسی",
    "fa_AF-formal": "Persian (Afghanistan)",
    "fa_AF-native": "فارسی (افغانستان)",
    "fa_IR-formal": "Persian (Iran)",
    "fa_IR-native": "فارسی (ایران)",
    "ff-formal": "Fulah",
    "ff-native": "Pulaar",
    "ff_CM-formal": "Fulah (Cameroon)",
    "ff_CM-native": "Pulaar (Kameruun)",
    "ff_GN-formal": "Fulah (Guinea)",
    "ff_GN-native": "Pulaar (Gine)",
    "ff_MR-formal": "Fulah (Mauritania)",
    "ff_MR-native": "Pulaar (Muritani)",
    "ff_SN-formal": "Fulah (Senegal)",
    "ff_SN-native": "Pulaar (Senegaal)",
    "fi-formal": "Finnish",
    "fi-native": "suomi",
    "fi_FI-formal": "Finnish (Finland)",
    "fi_FI-native": "suomi (Suomi)",
    "fil-formal": "Filipino",
    "fil_PH-formal": "Filipino (Philippines)",
    "fil_PH-native": "Filipino (Pilipinas)",
    "fo-formal": "Faroese",
    "fo-native": "føroyskt",
    "fo_DK-formal": "Faroese (Denmark)",
    "fo_DK-native": "føroyskt (Danmark)",
    "fo_FO-formal": "Faroese (Faroe Islands)",
    "fo_FO-native": "føroyskt (Føroyar)",
    "fr-formal": "French",
    "fr-native": "français",
    "fr_BE-formal": "French (Belgium)",
    "fr_BE-native": "français (Belgique)",
    "fr_BF-formal": "French (Burkina Faso)",
    "fr_BF-native": "français (Burkina Faso)",
    "fr_BI-formal": "French (Burundi)",
    "fr_BI-native": "français (Burundi)",
    "fr_BJ-formal": "French (Benin)",
    "fr_BJ-native": "français (Bénin)",
    "fr_BL-formal": "French (St. Barthélemy)",
    "fr_BL-native": "français (Saint-Barthélemy)",
    "fr_CA-formal": "French (Canada)",
    "fr_CA-native": "français (Canada)",
    "fr_CD-formal": "French (Congo - Kinshasa)",
    "fr_CD-native": "français (Congo-Kinshasa)",
    "fr_CF-formal": "French (Central African Republic)",
    "fr_CF-native": "français (République centrafricaine)",
    "fr_CG-formal": "French (Congo - Brazzaville)",
    "fr_CG-native": "français (Congo-Brazzaville)",
    "fr_CH-formal": "French (Switzerland)",
    "fr_CH-native": "français (Suisse)",
    "fr_CI-formal": "French (Côte d’Ivoire)",
    "fr_CI-native": "français (Côte d’Ivoire)",
    "fr_CM-formal": "French (Cameroon)",
    "fr_CM-native": "français (Cameroun)",
    "fr_DJ-formal": "French (Djibouti)",
    "fr_DJ-native": "français (Djibouti)",
    "fr_DZ-formal": "French (Algeria)",
    "fr_DZ-native": "français (Algérie)",
    "fr_FR-formal": "French (France)",
    "fr_FR-native": "français (France)",
    "fr_GA-formal": "French (Gabon)",
    "fr_GA-native": "français (Gabon)",
    "fr_GF-formal": "French (French Guiana)",
    "fr_GF-native": "français (Guyane française)",
    "fr_GN-formal": "French (Guinea)",
    "fr_GN-native": "français (Guinée)",
    "fr_GP-formal": "French (Guadeloupe)",
    "fr_GP-native": "français (Guadeloupe)",
    "fr_GQ-formal": "French (Equatorial Guinea)",
    "fr_GQ-native": "français (Guinée équatoriale)",
    "fr_HT-formal": "French (Haiti)",
    "fr_HT-native": "français (Haïti)",
    "fr_KM-formal": "French (Comoros)",
    "fr_KM-native": "français (Comores)",
    "fr_LU-formal": "French (Luxembourg)",
    "fr_LU-native": "français (Luxembourg)",
    "fr_MA-formal": "French (Morocco)",
    "fr_MA-native": "français (Maroc)",
    "fr_MC-formal": "French (Monaco)",
    "fr_MC-native": "français (Monaco)",
    "fr_MF-formal": "French (St. Martin)",
    "fr_MF-native": "français (Saint-Martin)",
    "fr_MG-formal": "French (Madagascar)",
    "fr_MG-native": "français (Madagascar)",
    "fr_ML-formal": "French (Mali)",
    "fr_ML-native": "français (Mali)",
    "fr_MQ-formal": "French (Martinique)",
    "fr_MQ-native": "français (Martinique)",
    "fr_MR-formal": "French (Mauritania)",
    "fr_MR-native": "français (Mauritanie)",
    "fr_MU-formal": "French (Mauritius)",
    "fr_MU-native": "français (Maurice)",
    "fr_NC-formal": "French (New Caledonia)",
    "fr_NC-native": "français (Nouvelle-Calédonie)",
    "fr_NE-formal": "French (Niger)",
    "fr_NE-native": "français (Niger)",
    "fr_PF-formal": "French (French Polynesia)",
    "fr_PF-native": "français (Polynésie française)",
    "fr_PM-formal": "French (St. Pierre & Miquelon)",
    "fr_PM-native": "français (Saint-Pierre-et-Miquelon)",
    "fr_RE-formal": "French (Réunion)",
    "fr_RE-native": "français (La Réunion)",
    "fr_RW-formal": "French (Rwanda)",
    "fr_RW-native": "français (Rwanda)",
    "fr_SC-formal": "French (Seychelles)",
    "fr_SC-native": "français (Seychelles)",
    "fr_SN-formal": "French (Senegal)",
    "fr_SN-native": "français (Sénégal)",
    "fr_SY-formal": "French (Syria)",
    "fr_SY-native": "français (Syrie)",
    "fr_TD-formal": "French (Chad)",
    "fr_TD-native": "français (Tchad)",
    "fr_TG-formal": "French (Togo)",
    "fr_TG-native": "français (Togo)",
    "fr_TN-formal": "French (Tunisia)",
    "fr_TN-native": "français (Tunisie)",
    "fr_VU-formal": "French (Vanuatu)",
    "fr_VU-native": "français (Vanuatu)",
    "fr_WF-formal": "French (Wallis & Futuna)",
    "fr_WF-native": "français (Wallis-et-Futuna)",
    "fr_YT-formal": "French (Mayotte)",
    "fr_YT-native": "français (Mayotte)",
    "fur-formal": "Friulian",
    "fur-native": "furlan",
    "fur_IT-formal": "Friulian (Italy)",
    "fur_IT-native": "furlan (Italie)",
    "fy-formal": "Western Frisian",
    "fy-native": "Frysk",
    "fy_NL-formal": "Western Frisian (Netherlands)",
    "fy_NL-native": "Frysk (Nederlân)",
    "ga-formal": "Irish",
    "ga-native": "Gaeilge",
    "ga_IE-formal": "Irish (Ireland)",
    "ga_IE-native": "Gaeilge (Éire)",
    "gd-formal": "Scottish Gaelic",
    "gd-native": "Gàidhlig",
    "gd_GB-formal": "Scottish Gaelic (United Kingdom)",
    "gd_GB-native": "Gàidhlig (An Rìoghachd Aonaichte)",
    "gl-formal": "Galician",
    "gl-native": "galego",
    "gl_ES-formal": "Galician (Spain)",
    "gl_ES-native": "galego (España)",
    "gsw-formal": "Swiss German",
    "gsw-native": "Schwiizertüütsch",
    "gsw_CH-formal": "Swiss German (Switzerland)",
    "gsw_CH-native": "Schwiizertüütsch (Schwiiz)",
    "gsw_FR-formal": "Swiss German (France)",
    "gsw_FR-native": "Schwiizertüütsch (Frankriich)",
    "gsw_LI-formal": "Swiss German (Liechtenstein)",
    "gsw_LI-native": "Schwiizertüütsch (Liächteschtäi)",
    "gu-formal": "Gujarati",
    "gu-native": "ગુજરાતી",
    "gu_IN-formal": "Gujarati (India)",
    "gu_IN-native": "ગુજરાતી (ભારત)",
    "guz-formal": "Gusii",
    "guz-native": "Ekegusii",
    "guz_KE-formal": "Gusii (Kenya)",
    "guz_KE-native": "Ekegusii (Kenya)",
    "gv-formal": "Manx",
    "gv-native": "Gaelg",
    "gv_IM-formal": "Manx (Isle of Man)",
    "gv_IM-native": "Gaelg (Ellan Vannin)",
    "ha-formal": "Hausa",
    "ha_GH-formal": "Hausa (Ghana)",
    "ha_GH-native": "Hausa (Gana)",
    "ha_NE-formal": "Hausa (Niger)",
    "ha_NE-native": "Hausa (Nijar)",
    "ha_NG-formal": "Hausa (Nigeria)",
    "ha_NG-native": "Hausa (Najeriya)",
    "haw-formal": "Hawaiian",
    "haw-native": "ʻŌlelo Hawaiʻi",
    "haw_US-formal": "Hawaiian (United States)",
    "haw_US-native": "ʻŌlelo Hawaiʻi (ʻAmelika Hui Pū ʻIa)",
    "he-formal": "Hebrew",
    "he-native": "עברית",
    "he_IL-formal": "Hebrew (Israel)",
    "he_IL-native": "עברית (ישראל)",
    "hi-formal": "Hindi",
    "hi-native": "हिन्दी",
    "hi_IN-formal": "Hindi (India)",
    "hi_IN-native": "हिन्दी (भारत)",
    "hr-formal": "Croatian",
    "hr-native": "hrvatski",
    "hr_BA-formal": "Croatian (Bosnia & Herzegovina)",
    "hr_BA-native": "hrvatski (Bosna i Hercegovina)",
    "hr_HR-formal": "Croatian (Croatia)",
    "hr_HR-native": "hrvatski (Hrvatska)",
    "hsb-formal": "Upper Sorbian",
    "hsb-native": "hornjoserbšćina",
    "hsb_DE-formal": "Upper Sorbian (Germany)",
    "hsb_DE-native": "hornjoserbšćina (Němska)",
    "hu-formal": "Hungarian",
    "hu-native": "magyar",
    "hu_HU-formal": "Hungarian (Hungary)",
    "hu_HU-native": "magyar (Magyarország)",
    "hy-formal": "Armenian",
    "hy-native": "հայերեն",
    "hy_AM-formal": "Armenian (Armenia)",
    "hy_AM-native": "հայերեն (Հայաստան)",
    "id-formal": "Indonesian",
    "id-native": "Indonesia",
    "id_ID-formal": "Indonesian (Indonesia)",
    "id_ID-native": "Indonesia (Indonesia)",
    "ig-formal": "Igbo",
    "ig_NG-formal": "Igbo (Nigeria)",
    "ig_NG-native": "Igbo (Naịjịrịa)",
    "ii-formal": "Sichuan Yi",
    "ii-native": "ꆈꌠꉙ",
    "ii_CN-formal": "Sichuan Yi (China)",
    "ii_CN-native": "ꆈꌠꉙ (ꍏꇩ)",
    "is-formal": "Icelandic",
    "is-native": "íslenska",
    "is_IS-formal": "Icelandic (Iceland)",
    "is_IS-native": "íslenska (Ísland)",
    "it-formal": "Italian",
    "it-native": "italiano",
    "it_CH-formal": "Italian (Switzerland)",
    "it_CH-native": "italiano (Svizzera)",
    "it_IT-formal": "Italian (Italy)",
    "it_IT-native": "italiano (Italia)",
    "it_SM-formal": "Italian (San Marino)",
    "it_SM-native": "italiano (San Marino)",
    "it_VA-formal": "Italian (Vatican City)",
    "it_VA-native": "italiano (Città del Vaticano)",
    "ja-formal": "Japanese",
    "ja-native": "日本語",
    "ja_JP-formal": "Japanese (Japan)",
    "ja_JP-native": "日本語 (日本)",
    "jgo-formal": "Ngomba",
    "jgo-native": "Ndaꞌa",
    "jgo_CM-formal": "Ngomba (Cameroon)",
    "jgo_CM-native": "Ndaꞌa (Kamɛlûn)",
    "jmc-formal": "Machame",
    "jmc-native": "Kimachame",
    "jmc_TZ-formal": "Machame (Tanzania)",
    "jmc_TZ-native": "Kimachame (Tanzania)",
    "ka-formal": "Georgian",
    "ka-native": "ქართული",
    "ka_GE-formal": "Georgian (Georgia)",
    "ka_GE-native": "ქართული (საქართველო)",
    "kab-formal": "Kabyle",
    "kab-native": "Taqbaylit",
    "kab_DZ-formal": "Kabyle (Algeria)",
    "kab_DZ-native": "Taqbaylit (Lezzayer)",
    "kam-formal": "Kamba",
    "kam-native": "Kikamba",
    "kam_KE-formal": "Kamba (Kenya)",
    "kam_KE-native": "Kikamba (Kenya)",
    "kde-formal": "Makonde",
    "kde-native": "Chimakonde",
    "kde_TZ-formal": "Makonde (Tanzania)",
    "kde_TZ-native": "Chimakonde (Tanzania)",
    "kea-formal": "Kabuverdianu",
    "kea-native": "kabuverdianu",
    "kea_CV-formal": "Kabuverdianu (Cape Verde)",
    "kea_CV-native": "kabuverdianu (Kabu Verdi)",
    "khq-formal": "Koyra Chiini",
    "khq-native": "Koyra ciini",
    "khq_ML-formal": "Koyra Chiini (Mali)",
    "khq_ML-native": "Koyra ciini (Maali)",
    "ki-formal": "Kikuyu",
    "ki-native": "Gikuyu",
    "ki_KE-formal": "Kikuyu (Kenya)",
    "ki_KE-native": "Gikuyu (Kenya)",
    "kk-formal": "Kazakh",
    "kk-native": "қазақ тілі",
    "kk_KZ-formal": "Kazakh (Kazakhstan)",
    "kk_KZ-native": "қазақ тілі (Қазақстан)",
    "kkj-formal": "Kako",
    "kkj-native": "kakɔ",
    "kkj_CM-formal": "Kako (Cameroon)",
    "kkj_CM-native": "kakɔ (Kamɛrun)",
    "kl-formal": "Kalaallisut",
    "kl-native": "kalaallisut",
    "kl_GL-formal": "Kalaallisut (Greenland)",
    "kl_GL-native": "kalaallisut (Kalaallit Nunaat)",
    "kln-formal": "Kalenjin",
    "kln_KE-formal": "Kalenjin (Kenya)",
    "kln_KE-native": "Kalenjin (Emetab Kenya)",
    "km-formal": "Khmer",
    "km-native": "ខ្មែរ",
    "km_KH-formal": "Khmer (Cambodia)",
    "km_KH-native": "ខ្មែរ (កម្ពុជា)",
    "kn-formal": "Kannada",
    "kn-native": "ಕನ್ನಡ",
    "kn_IN-formal": "Kannada (India)",
    "kn_IN-native": "ಕನ್ನಡ (ಭಾರತ)",
    "ko-formal": "Korean",
    "ko-native": "한국어",
    "ko_KP-formal": "Korean (North Korea)",
    "ko_KP-native": "한국어(조선민주주의인민공화국)",
    "ko_KR-formal": "Korean (South Korea)",
    "ko_KR-native": "한국어(대한민국)",
    "kok-formal": "Konkani",
    "kok-native": "कोंकणी",
    "kok_IN-formal": "Konkani (India)",
    "kok_IN-native": "कोंकणी (भारत)",
    "ks-formal": "Kashmiri",
    "ks-native": "کٲشُر",
    "ks_IN-formal": "Kashmiri (India)",
    "ks_IN-native": "کٲشُر (ہِنٛدوستان)",
    "ksb-formal": "Shambala",
    "ksb-native": "Kishambaa",
    "ksb_TZ-formal": "Shambala (Tanzania)",
    "ksb_TZ-native": "Kishambaa (Tanzania)",
    "ksf-formal": "Bafia",
    "ksf-native": "rikpa",
    "ksf_CM-formal": "Bafia (Cameroon)",
    "ksf_CM-native": "rikpa (kamɛrún)",
    "ksh-formal": "Colognian",
    "ksh-native": "Kölsch",
    "ksh_DE-formal": "Colognian (Germany)",
    "ksh_DE-native": "Kölsch en Doütschland",
    "kw-formal": "Cornish",
    "kw-native": "kernewek",
    "kw_GB-formal": "Cornish (United Kingdom)",
    "kw_GB-native": "kernewek (Rywvaneth Unys)",
    "ky-formal": "Kyrgyz",
    "ky-native": "кыргызча",
    "ky_KG-formal": "Kyrgyz (Kyrgyzstan)",
    "ky_KG-native": "кыргызча (Кыргызстан)",
    "lag-formal": "Langi",
    "lag-native": "Kɨlaangi",
    "lag_TZ-formal": "Langi (Tanzania)",
    "lag_TZ-native": "Kɨlaangi (Taansanía)",
    "lb-formal": "Luxembourgish",
    "lb-native": "Lëtzebuergesch",
    "lb_LU-formal": "Luxembourgish (Luxembourg)",
    "lb_LU-native": "Lëtzebuergesch (Lëtzebuerg)",
    "lg-formal": "Ganda",
    "lg-native": "Luganda",
    "lg_UG-formal": "Ganda (Uganda)",
    "lg_UG-native": "Luganda (Yuganda)",
    "lkt-formal": "Lakota",
    "lkt-native": "Lakȟólʼiyapi",
    "lkt_US-formal": "Lakota (United States)",
    "lkt_US-native": "Lakȟólʼiyapi (Mílahaŋska Tȟamákȟočhe)",
    "ln-formal": "Lingala",
    "ln-native": "lingála",
    "ln_AO-formal": "Lingala (Angola)",
    "ln_AO-native": "lingála (Angóla)",
    "ln_CD-formal": "Lingala (Congo - Kinshasa)",
    "ln_CD-native": "lingála (Republíki ya Kongó Demokratíki)",
    "ln_CF-formal": "Lingala (Central African Republic)",
    "ln_CF-native": "lingála (Repibiki ya Afríka ya Káti)",
    "ln_CG-formal": "Lingala (Congo - Brazzaville)",
    "ln_CG-native": "lingála (Kongo)",
    "lo-formal": "Lao",
    "lo-native": "ລາວ",
    "lo_LA-formal": "Lao (Laos)",
    "lo_LA-native": "ລາວ (ລາວ)",
    "lrc-formal": "Northern Luri",
    "lrc-native": "لۊری شومالی",
    "lrc_IQ-formal": "Northern Luri (Iraq)",
    "lrc_IQ-native": "لۊری شومالی (IQ)",
    "lrc_IR-formal": "Northern Luri (Iran)",
    "lrc_IR-native": "لۊری شومالی (IR)",
    "lt-formal": "Lithuanian",
    "lt-native": "lietuvių",
    "lt_LT-formal": "Lithuanian (Lithuania)",
    "lt_LT-native": "lietuvių (Lietuva)",
    "lu-formal": "Luba-Katanga",
    "lu-native": "Tshiluba",
    "lu_CD-formal": "Luba-Katanga (Congo - Kinshasa)",
    "lu_CD-native": "Tshiluba (Ditunga wa Kongu)",
    "luo-formal": "Luo",
    "luo-native": "Dholuo",
    "luo_KE-formal": "Luo (Kenya)",
    "luo_KE-native": "Dholuo (Kenya)",
    "luy-formal": "Luyia",
    "luy-native": "Luluhia",
    "luy_KE-formal": "Luyia (Kenya)",
    "luy_KE-native": "Luluhia (Kenya)",
    "lv-formal": "Latvian",
    "lv-native": "latviešu",
    "lv_LV-formal": "Latvian (Latvia)",
    "lv_LV-native": "latviešu (Latvija)",
    "mas-formal": "Masai",
    "mas-native": "Maa",
    "mas_KE-formal": "Masai (Kenya)",
    "mas_KE-native": "Maa (Kenya)",
    "mas_TZ-formal": "Masai (Tanzania)",
    "mas_TZ-native": "Maa (Tansania)",
    "mer-formal": "Meru",
    "mer-native": "Kĩmĩrũ",
    "mer_KE-formal": "Meru (Kenya)",
    "mer_KE-native": "Kĩmĩrũ (Kenya)",
    "mfe-formal": "Morisyen",
    "mfe-native": "kreol morisien",
    "mfe_MU-formal": "Morisyen (Mauritius)",
    "mfe_MU-native": "kreol morisien (Moris)",
    "mg-formal": "Malagasy",
    "mg_MG-formal": "Malagasy (Madagascar)",
    "mg_MG-native": "Malagasy (Madagasikara)",
    "mgh-formal": "Makhuwa-Meetto",
    "mgh-native": "Makua",
    "mgh_MZ-formal": "Makhuwa-Meetto (Mozambique)",
    "mgh_MZ-native": "Makua (Umozambiki)",
    "mgo-formal": "Metaʼ",
    "mgo-native": "metaʼ",
    "mgo_CM-formal": "Metaʼ (Cameroon)",
    "mgo_CM-native": "metaʼ (Kamalun)",
    "mk-formal": "Macedonian",
    "mk-native": "македонски",
    "mk_MK-formal": "Macedonian (Macedonia)",
    "mk_MK-native": "македонски (Македонија)",
    "ml-formal": "Malayalam",
    "ml-native": "മലയാളം",
    "ml_IN-formal": "Malayalam (India)",
    "ml_IN-native": "മലയാളം (ഇന്ത്യ)",
    "mn-formal": "Mongolian",
    "mn-native": "монгол",
    "mn_MN-formal": "Mongolian (Mongolia)",
    "mn_MN-native": "монгол (Монгол)",
    "mr-formal": "Marathi",
    "mr-native": "मराठी",
    "mr_IN-formal": "Marathi (India)",
    "mr_IN-native": "मराठी (भारत)",
    "ms-formal": "Malay",
    "ms-native": "Melayu",
    "ms_BN-formal": "Malay (Brunei)",
    "ms_BN-native": "Melayu (Brunei)",
    "ms_MY-formal": "Malay (Malaysia)",
    "ms_MY-native": "Melayu (Malaysia)",
    "ms_SG-formal": "Malay (Singapore)",
    "ms_SG-native": "Melayu (Singapura)",
    "mt-formal": "Maltese",
    "mt-native": "Malti",
    "mt_MT-formal": "Maltese (Malta)",
    "mt_MT-native": "Malti (Malta)",
    "mua-formal": "Mundang",
    "mua-native": "MUNDAŊ",
    "mua_CM-formal": "Mundang (Cameroon)",
    "mua_CM-native": "MUNDAŊ (kameruŋ)",
    "my-formal": "Burmese",
    "my-native": "မြန်မာ",
    "my_MM-formal": "Burmese (Myanmar [Burma])",
    "my_MM-native": "မြန်မာ (မြန်မာ)",
    "mzn-formal": "Mazanderani",
    "mzn-native": "مازرونی",
    "mzn_IR-formal": "Mazanderani (Iran)",
    "mzn_IR-native": "مازرونی (ایران)",
    "naq-formal": "Nama",
    "naq-native": "Khoekhoegowab",
    "naq_NA-formal": "Nama (Namibia)",
    "naq_NA-native": "Khoekhoegowab (Namibiab)",
    "nb-formal": "Norwegian Bokmål",
    "nb-native": "norsk bokmål",
    "nb_NO-formal": "Norwegian Bokmål (Norway)",
    "nb_NO-native": "norsk bokmål (Norge)",
    "nb_SJ-formal": "Norwegian Bokmål (Svalbard & Jan Mayen)",
    "nb_SJ-native": "norsk bokmål (Svalbard og Jan Mayen)",
    "nd-formal": "North Ndebele",
    "nd-native": "isiNdebele",
    "nd_ZW-formal": "North Ndebele (Zimbabwe)",
    "nd_ZW-native": "isiNdebele (Zimbabwe)",
    "nds-formal": "Low German",
    "nds-native": "nds",
    "nds_DE-formal": "Low German (Germany)",
    "nds_DE-native": "nds (DE)",
    "nds_NL-formal": "Low German (Netherlands)",
    "nds_NL-native": "nds (NL)",
    "ne-formal": "Nepali",
    "ne-native": "नेपाली",
    "ne_IN-formal": "Nepali (India)",
    "ne_IN-native": "नेपाली (भारत)",
    "ne_NP-formal": "Nepali (Nepal)",
    "ne_NP-native": "नेपाली (नेपाल)",
    "nl-formal": "Dutch",
    "nl-native": "Nederlands",
    "nl_AW-formal": "Dutch (Aruba)",
    "nl_AW-native": "Nederlands (Aruba)",
    "nl_BE-formal": "Dutch (Belgium)",
    "nl_BE-native": "Nederlands (België)",
    "nl_BQ-formal": "Dutch (Caribbean Netherlands)",
    "nl_BQ-native": "Nederlands (Caribisch Nederland)",
    "nl_CW-formal": "Dutch (Curaçao)",
    "nl_CW-native": "Nederlands (Curaçao)",
    "nl_NL-formal": "Dutch (Netherlands)",
    "nl_NL-native": "Nederlands (Nederland)",
    "nl_SR-formal": "Dutch (Suriname)",
    "nl_SR-native": "Nederlands (Suriname)",
    "nl_SX-formal": "Dutch (Sint Maarten)",
    "nl_SX-native": "Nederlands (Sint-Maarten)",
    "nmg-formal": "Kwasio",
    "nmg-native": "nmg",
    "nmg_CM-formal": "Kwasio (Cameroon)",
    "nmg_CM-native": "nmg (Kamerun)",
    "nn-formal": "Norwegian Nynorsk",
    "nn-native": "nynorsk",
    "nn_NO-formal": "Norwegian Nynorsk (Norway)",
    "nn_NO-native": "nynorsk (Noreg)",
    "nnh-formal": "Ngiemboon",
    "nnh-native": "Shwóŋò ngiembɔɔn",
    "nnh_CM-formal": "Ngiemboon (Cameroon)",
    "nnh_CM-native": "Shwóŋò ngiembɔɔn (Kàmalûm)",
    "nus-formal": "Nuer",
    "nus-native": "Thok Nath",
    "nus_SS-formal": "Nuer (South Sudan)",
    "nus_SS-native": "Thok Nath (SS)",
    "nyn-formal": "Nyankole",
    "nyn-native": "Runyankore",
    "nyn_UG-formal": "Nyankole (Uganda)",
    "nyn_UG-native": "Runyankore (Uganda)",
    "om-formal": "Oromo",
    "om-native": "Oromoo",
    "om_ET-formal": "Oromo (Ethiopia)",
    "om_ET-native": "Oromoo (Itoophiyaa)",
    "om_KE-formal": "Oromo (Kenya)",
    "om_KE-native": "Oromoo (Keeniyaa)",
    "or-formal": "Odia",
    "or-native": "ଓଡ଼ିଆ",
    "or_IN-formal": "Odia (India)",
    "or_IN-native": "ଓଡ଼ିଆ (ଭାରତ)",
    "os-formal": "Ossetic",
    "os-native": "ирон",
    "os_GE-formal": "Ossetic (Georgia)",
    "os_GE-native": "ирон (Гуырдзыстон)",
    "os_RU-formal": "Ossetic (Russia)",
    "os_RU-native": "ирон (Уӕрӕсе)",
    "pa-formal": "Punjabi",
    "pa-native": "ਪੰਜਾਬੀ",
    "pa_Arab-formal": "Punjabi (Arabic)",
    "pa_Arab-native": "پنجابی (عربی)",
    "pa_Arab_PK-formal": "Punjabi (Arabic, Pakistan)",
    "pa_Arab_PK-native": "پنجابی (عربی, پاکستان)",
    "pa_Guru-formal": "Punjabi (Gurmukhi)",
    "pa_Guru-native": "ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)",
    "pa_Guru_IN-formal": "Punjabi (Gurmukhi, India)",
    "pa_Guru_IN-native": "ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ, ਭਾਰਤ)",
    "pl-formal": "Polish",
    "pl-native": "polski",
    "pl_PL-formal": "Polish (Poland)",
    "pl_PL-native": "polski (Polska)",
    "ps-formal": "Pashto",
    "ps-native": "پښتو",
    "ps_AF-formal": "Pashto (Afghanistan)",
    "ps_AF-native": "پښتو (افغانستان)",
    "pt-formal": "Portuguese",
    "pt-native": "português",
    "pt_AO-formal": "Portuguese (Angola)",
    "pt_AO-native": "português (Angola)",
    "pt_BR-formal": "Portuguese (Brazil)",
    "pt_BR-native": "português (Brasil)",
    "pt_CH-formal": "Portuguese (Switzerland)",
    "pt_CH-native": "português (Suíça)",
    "pt_CV-formal": "Portuguese (Cape Verde)",
    "pt_CV-native": "português (Cabo Verde)",
    "pt_GQ-formal": "Portuguese (Equatorial Guinea)",
    "pt_GQ-native": "português (Guiné Equatorial)",
    "pt_GW-formal": "Portuguese (Guinea-Bissau)",
    "pt_GW-native": "português (Guiné-Bissau)",
    "pt_LU-formal": "Portuguese (Luxembourg)",
    "pt_LU-native": "português (Luxemburgo)",
    "pt_MO-formal": "Portuguese (Macau SAR China)",
    "pt_MO-native": "português (Macau, RAE da China)",
    "pt_MZ-formal": "Portuguese (Mozambique)",
    "pt_MZ-native": "português (Moçambique)",
    "pt_PT-formal": "Portuguese (Portugal)",
    "pt_PT-native": "português (Portugal)",
    "pt_ST-formal": "Portuguese (São Tomé & Príncipe)",
    "pt_ST-native": "português (São Tomé e Príncipe)",
    "pt_TL-formal": "Portuguese (Timor-Leste)",
    "pt_TL-native": "português (Timor-Leste)",
    "qu-formal": "Quechua",
    "qu-native": "Runasimi",
    "qu_BO-formal": "Quechua (Bolivia)",
    "qu_BO-native": "Runasimi (Bolivia)",
    "qu_EC-formal": "Quechua (Ecuador)",
    "qu_EC-native": "Runasimi (Ecuador)",
    "qu_PE-formal": "Quechua (Peru)",
    "qu_PE-native": "Runasimi (Perú)",
    "rm-formal": "Romansh",
    "rm-native": "rumantsch",
    "rm_CH-formal": "Romansh (Switzerland)",
    "rm_CH-native": "rumantsch (Svizra)",
    "rn-formal": "Rundi",
    "rn-native": "Ikirundi",
    "rn_BI-formal": "Rundi (Burundi)",
    "rn_BI-native": "Ikirundi (Uburundi)",
    "ro-formal": "Romanian",
    "ro-native": "română",
    "ro_MD-formal": "Romanian (Moldova)",
    "ro_MD-native": "română (Republica Moldova)",
    "ro_RO-formal": "Romanian (Romania)",
    "ro_RO-native": "română (România)",
    "rof-formal": "Rombo",
    "rof-native": "Kihorombo",
    "rof_TZ-formal": "Rombo (Tanzania)",
    "rof_TZ-native": "Kihorombo (Tanzania)",
    "ru-formal": "Russian",
    "ru-native": "русский",
    "ru_BY-formal": "Russian (Belarus)",
    "ru_BY-native": "русский (Беларусь)",
    "ru_KG-formal": "Russian (Kyrgyzstan)",
    "ru_KG-native": "русский (Киргизия)",
    "ru_KZ-formal": "Russian (Kazakhstan)",
    "ru_KZ-native": "русский (Казахстан)",
    "ru_MD-formal": "Russian (Moldova)",
    "ru_MD-native": "русский (Молдова)",
    "ru_RU-formal": "Russian (Russia)",
    "ru_RU-native": "русский (Россия)",
    "ru_UA-formal": "Russian (Ukraine)",
    "ru_UA-native": "русский (Украина)",
    "rw-formal": "Kinyarwanda",
    "rw_RW-formal": "Kinyarwanda (Rwanda)",
    "rw_RW-native": "Kinyarwanda (U Rwanda)",
    "rwk-formal": "Rwa",
    "rwk-native": "Kiruwa",
    "rwk_TZ-formal": "Rwa (Tanzania)",
    "rwk_TZ-native": "Kiruwa (Tanzania)",
    "sah-formal": "Sakha",
    "sah-native": "саха тыла",
    "sah_RU-formal": "Sakha (Russia)",
    "sah_RU-native": "саха тыла (Арассыыйа)",
    "saq-formal": "Samburu",
    "saq-native": "Kisampur",
    "saq_KE-formal": "Samburu (Kenya)",
    "saq_KE-native": "Kisampur (Kenya)",
    "sbp-formal": "Sangu",
    "sbp-native": "Ishisangu",
    "sbp_TZ-formal": "Sangu (Tanzania)",
    "sbp_TZ-native": "Ishisangu (Tansaniya)",
    "se-formal": "Northern Sami",
    "se-native": "davvisámegiella",
    "se_FI-formal": "Northern Sami (Finland)",
    "se_FI-native": "davvisámegiella (Suopma)",
    "se_NO-formal": "Northern Sami (Norway)",
    "se_NO-native": "davvisámegiella (Norga)",
    "se_SE-formal": "Northern Sami (Sweden)",
    "se_SE-native": "davvisámegiella (Ruoŧŧa)",
    "seh-formal": "Sena",
    "seh-native": "sena",
    "seh_MZ-formal": "Sena (Mozambique)",
    "seh_MZ-native": "sena (Moçambique)",
    "ses-formal": "Koyraboro Senni",
    "ses-native": "Koyraboro senni",
    "ses_ML-formal": "Koyraboro Senni (Mali)",
    "ses_ML-native": "Koyraboro senni (Maali)",
    "sg-formal": "Sango",
    "sg-native": "Sängö",
    "sg_CF-formal": "Sango (Central African Republic)",
    "sg_CF-native": "Sängö (Ködörösêse tî Bêafrîka)",
    "shi-formal": "Tachelhit",
    "shi-native": "ⵜⴰⵛⵍⵃⵉⵜ",
    "shi_Latn-formal": "Tachelhit (Latin)",
    "shi_Latn-native": "Tashelḥiyt (Latn)",
    "shi_Latn_MA-formal": "Tachelhit (Latin, Morocco)",
    "shi_Latn_MA-native": "Tashelḥiyt (Latn, lmɣrib)",
    "shi_Tfng-formal": "Tachelhit (Tifinagh)",
    "shi_Tfng-native": "ⵜⴰⵛⵍⵃⵉⵜ (Tfng)",
    "shi_Tfng_MA-formal": "Tachelhit (Tifinagh, Morocco)",
    "shi_Tfng_MA-native": "ⵜⴰⵛⵍⵃⵉⵜ (Tfng, ⵍⵎⵖⵔⵉⴱ)",
    "si-formal": "Sinhala",
    "si-native": "සිංහල",
    "si_LK-formal": "Sinhala (Sri Lanka)",
    "si_LK-native": "සිංහල (ශ්‍රී ලංකාව)",
    "sk-formal": "Slovak",
    "sk-native": "slovenčina",
    "sk_SK-formal": "Slovak (Slovakia)",
    "sk_SK-native": "slovenčina (Slovensko)",
    "sl-formal": "Slovenian",
    "sl-native": "slovenščina",
    "sl_SI-formal": "Slovenian (Slovenia)",
    "sl_SI-native": "slovenščina (Slovenija)",
    "smn-formal": "Inari Sami",
    "smn-native": "anarâškielâ",
    "smn_FI-formal": "Inari Sami (Finland)",
    "smn_FI-native": "anarâškielâ (Suomâ)",
    "sn-formal": "Shona",
    "sn-native": "chiShona",
    "sn_ZW-formal": "Shona (Zimbabwe)",
    "sn_ZW-native": "chiShona (Zimbabwe)",
    "so-formal": "Somali",
    "so-native": "Soomaali",
    "so_DJ-formal": "Somali (Djibouti)",
    "so_DJ-native": "Soomaali (Jabuuti)",
    "so_ET-formal": "Somali (Ethiopia)",
    "so_ET-native": "Soomaali (Itoobiya)",
    "so_KE-formal": "Somali (Kenya)",
    "so_KE-native": "Soomaali (Kiiniya)",
    "so_SO-formal": "Somali (Somalia)",
    "so_SO-native": "Soomaali (Soomaaliya)",
    "sq-formal": "Albanian",
    "sq-native": "shqip",
    "sq_AL-formal": "Albanian (Albania)",
    "sq_AL-native": "shqip (Shqipëri)",
    "sq_MK-formal": "Albanian (Macedonia)",
    "sq_MK-native": "shqip (Maqedoni)",
    "sq_XK-formal": "Albanian (Kosovo)",
    "sq_XK-native": "shqip (Kosovë)",
    "sr-formal": "Serbian",
    "sr-native": "српски",
    "sr_Cyrl-formal": "Serbian (Cyrillic)",
    "sr_Cyrl-native": "српски (ћирилица)",
    "sr_Cyrl_BA-formal": "Serbian (Cyrillic, Bosnia & Herzegovina)",
    "sr_Cyrl_BA-native": "српски (ћирилица, Босна и Херцеговина)",
    "sr_Cyrl_ME-formal": "Serbian (Cyrillic, Montenegro)",
    "sr_Cyrl_ME-native": "српски (ћирилица, Црна Гора)",
    "sr_Cyrl_RS-formal": "Serbian (Cyrillic, Serbia)",
    "sr_Cyrl_RS-native": "српски (ћирилица, Србија)",
    "sr_Cyrl_XK-formal": "Serbian (Cyrillic, Kosovo)",
    "sr_Cyrl_XK-native": "српски (ћирилица, Косово)",
    "sr_Latn-formal": "Serbian (Latin)",
    "sr_Latn-native": "srpski (latinica)",
    "sr_Latn_BA-formal": "Serbian (Latin, Bosnia & Herzegovina)",
    "sr_Latn_BA-native": "srpski (latinica, Bosna i Hercegovina)",
    "sr_Latn_ME-formal": "Serbian (Latin, Montenegro)",
    "sr_Latn_ME-native": "srpski (latinica, Crna Gora)",
    "sr_Latn_RS-formal": "Serbian (Latin, Serbia)",
    "sr_Latn_RS-native": "srpski (latinica, Srbija)",
    "sr_Latn_XK-formal": "Serbian (Latin, Kosovo)",
    "sr_Latn_XK-native": "srpski (latinica, Kosovo)",
    "sv-formal": "Swedish",
    "sv-native": "svenska",
    "sv_AX-formal": "Swedish (Åland Islands)",
    "sv_AX-native": "svenska (Åland)",
    "sv_FI-formal": "Swedish (Finland)",
    "sv_FI-native": "svenska (Finland)",
    "sv_SE-formal": "Swedish (Sweden)",
    "sv_SE-native": "svenska (Sverige)",
    "sw-formal": "Swahili",
    "sw-native": "Kiswahili",
    "sw_CD-formal": "Swahili (Congo - Kinshasa)",
    "sw_CD-native": "Kiswahili (Jamhuri ya Kidemokrasia ya Kongo)",
    "sw_KE-formal": "Swahili (Kenya)",
    "sw_KE-native": "Kiswahili (Kenya)",
    "sw_TZ-formal": "Swahili (Tanzania)",
    "sw_TZ-native": "Kiswahili (Tanzania)",
    "sw_UG-formal": "Swahili (Uganda)",
    "sw_UG-native": "Kiswahili (Uganda)",
    "ta-formal": "Tamil",
    "ta-native": "தமிழ்",
    "ta_IN-formal": "Tamil (India)",
    "ta_IN-native": "தமிழ் (இந்தியா)",
    "ta_LK-formal": "Tamil (Sri Lanka)",
    "ta_LK-native": "தமிழ் (இலங்கை)",
    "ta_MY-formal": "Tamil (Malaysia)",
    "ta_MY-native": "தமிழ் (மலேசியா)",
    "ta_SG-formal": "Tamil (Singapore)",
    "ta_SG-native": "தமிழ் (சிங்கப்பூர்)",
    "te-formal": "Telugu",
    "te-native": "తెలుగు",
    "te_IN-formal": "Telugu (India)",
    "te_IN-native": "తెలుగు (భారతదేశం)",
    "teo-formal": "Teso",
    "teo-native": "Kiteso",
    "teo_KE-formal": "Teso (Kenya)",
    "teo_KE-native": "Kiteso (Kenia)",
    "teo_UG-formal": "Teso (Uganda)",
    "teo_UG-native": "Kiteso (Uganda)",
    "tg-formal": "Tajik",
    "tg-native": "тоҷикӣ",
    "tg_TJ-formal": "Tajik (Tajikistan)",
    "tg_TJ-native": "тоҷикӣ (Тоҷикистон)",
    "th-formal": "Thai",
    "th-native": "ไทย",
    "th_TH-formal": "Thai (Thailand)",
    "th_TH-native": "ไทย (ไทย)",
    "ti-formal": "Tigrinya",
    "ti-native": "ትግርኛ",
    "ti_ER-formal": "Tigrinya (Eritrea)",
    "ti_ER-native": "ትግርኛ (ኤርትራ)",
    "ti_ET-formal": "Tigrinya (Ethiopia)",
    "ti_ET-native": "ትግርኛ (ኢትዮጵያ)",
    "to-formal": "Tongan",
    "to-native": "lea fakatonga",
    "to_TO-formal": "Tongan (Tonga)",
    "to_TO-native": "lea fakatonga (Tonga)",
    "tr-formal": "Turkish",
    "tr-native": "Türkçe",
    "tr_CY-formal": "Turkish (Cyprus)",
    "tr_CY-native": "Türkçe (Kıbrıs)",
    "tr_TR-formal": "Turkish (Turkey)",
    "tr_TR-native": "Türkçe (Türkiye)",
    "tt-formal": "Tatar",
    "tt-native": "татар",
    "tt_RU-formal": "Tatar (Russia)",
    "tt_RU-native": "татар (Россия)",
    "twq-formal": "Tasawaq",
    "twq-native": "Tasawaq senni",
    "twq_NE-formal": "Tasawaq (Niger)",
    "twq_NE-native": "Tasawaq senni (Nižer)",
    "tzm-formal": "Central Atlas Tamazight",
    "tzm-native": "Tamaziɣt n laṭlaṣ",
    "tzm_MA-formal": "Central Atlas Tamazight (Morocco)",
    "tzm_MA-native": "Tamaziɣt n laṭlaṣ (Meṛṛuk)",
    "ug-formal": "Uyghur",
    "ug-native": "ئۇيغۇرچە",
    "ug_CN-formal": "Uyghur (China)",
    "ug_CN-native": "ئۇيغۇرچە (جۇڭگو)",
    "uk-formal": "Ukrainian",
    "uk-native": "українська",
    "uk_UA-formal": "Ukrainian (Ukraine)",
    "uk_UA-native": "українська (Україна)",
    "ur-formal": "Urdu",
    "ur-native": "اردو",
    "ur_IN-formal": "Urdu (India)",
    "ur_IN-native": "اردو (بھارت)",
    "ur_PK-formal": "Urdu (Pakistan)",
    "ur_PK-native": "اردو (پاکستان)",
    "uz-formal": "Uzbek",
    "uz-native": "o‘zbek",
    "uz_Arab-formal": "Uzbek (Arabic)",
    "uz_Arab-native": "اوزبیک (عربی)",
    "uz_Arab_AF-formal": "Uzbek (Arabic, Afghanistan)",
    "uz_Arab_AF-native": "اوزبیک (عربی, افغانستان)",
    "uz_Cyrl-formal": "Uzbek (Cyrillic)",
    "uz_Cyrl-native": "ўзбекча (Кирил)",
    "uz_Cyrl_UZ-formal": "Uzbek (Cyrillic, Uzbekistan)",
    "uz_Cyrl_UZ-native": "ўзбекча (Кирил, Ўзбекистон)",
    "uz_Latn-formal": "Uzbek (Latin)",
    "uz_Latn-native": "o‘zbek (lotin)",
    "uz_Latn_UZ-formal": "Uzbek (Latin, Uzbekistan)",
    "uz_Latn_UZ-native": "o‘zbek (lotin, Oʻzbekiston)",
    "vai-formal": "Vai",
    "vai-native": "ꕙꔤ",
    "vai_Latn-formal": "Vai (Latin)",
    "vai_Latn-native": "Vai (Latn)",
    "vai_Latn_LR-formal": "Vai (Latin, Liberia)",
    "vai_Latn_LR-native": "Vai (Latn, Laibhiya)",
    "vai_Vaii-formal": "Vai (Vai)",
    "vai_Vaii-native": "ꕙꔤ (Vaii)",
    "vai_Vaii_LR-formal": "Vai (Vai, Liberia)",
    "vai_Vaii_LR-native": "ꕙꔤ (Vaii, ꕞꔤꔫꕩ)",
    "vi-formal": "Vietnamese",
    "vi-native": "Tiếng Việt",
    "vi_VN-formal": "Vietnamese (Vietnam)",
    "vi_VN-native": "Tiếng Việt (Việt Nam)",
    "vun-formal": "Vunjo",
    "vun-native": "Kyivunjo",
    "vun_TZ-formal": "Vunjo (Tanzania)",
    "vun_TZ-native": "Kyivunjo (Tanzania)",
    "wae-formal": "Walser",
    "wae_CH-formal": "Walser (Switzerland)",
    "wae_CH-native": "Walser (Schwiz)",
    "wo-formal": "Wolof",
    "wo_SN-formal": "Wolof (Senegal)",
    "wo_SN-native": "Wolof (Senegaal)",
    "xog-formal": "Soga",
    "xog-native": "Olusoga",
    "xog_UG-formal": "Soga (Uganda)",
    "xog_UG-native": "Olusoga (Yuganda)",
    "yav-formal": "Yangben",
    "yav-native": "nuasue",
    "yav_CM-formal": "Yangben (Cameroon)",
    "yav_CM-native": "nuasue (Kemelún)",
    "yi-formal": "Yiddish",
    "yi-native": "ייִדיש",
    "yi_001-formal": "Yiddish (World)",
    "yi_001-native": "ייִדיש (וועלט)",
    "yo-formal": "Yoruba",
    "yo-native": "Èdè Yorùbá",
    "yo_BJ-formal": "Yoruba (Benin)",
    "yo_BJ-native": "Èdè Yorùbá (Orílɛ́ède Bɛ̀nɛ̀)",
    "yo_NG-formal": "Yoruba (Nigeria)",
    "yo_NG-native": "Èdè Yorùbá (Orílẹ́ède Nàìjíríà)",
    "yue-formal": "Cantonese",
    "yue-native": "粵語",
    "yue_Hans-formal": "Cantonese (Simplified)",
    "yue_Hans-native": "粤语 (简体)",
    "yue_Hans_CN-formal": "Cantonese (Simplified, China)",
    "yue_Hans_CN-native": "粤语 (简体，中华人民共和国)",
    "yue_Hant-formal": "Cantonese (Traditional)",
    "yue_Hant-native": "粵語 (繁體)",
    "yue_Hant_HK-formal": "Cantonese (Traditional, Hong Kong SAR China)",
    "yue_Hant_HK-native": "粵語 (繁體，中華人民共和國香港特別行政區)",
    "zgh-formal": "Standard Moroccan Tamazight",
    "zgh-native": "ⵜⴰⵎⴰⵣⵉⵖⵜ",
    "zgh_MA-formal": "Standard Moroccan Tamazight (Morocco)",
    "zgh_MA-native": "ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)",
    "zh-formal": "Chinese",
    "zh-native": "中文",
    "zh_Hans-formal": "Chinese (Simplified)",
    "zh_Hans-native": "中文（简体）",
    "zh_Hans_CN-formal": "Chinese (Simplified, China)",
    "zh_Hans_CN-native": "中文（简体，中国）",
    "zh_Hans_HK-formal": "Chinese (Simplified, Hong Kong SAR China)",
    "zh_Hans_HK-native": "中文（简体，中国香港特别行政区）",
    "zh_Hans_MO-formal": "Chinese (Simplified, Macau SAR China)",
    "zh_Hans_MO-native": "中文（简体，中国澳门特别行政区）",
    "zh_Hans_SG-formal": "Chinese (Simplified, Singapore)",
    "zh_Hans_SG-native": "中文（简体，新加坡）",
    "zh_Hant-formal": "Chinese (Traditional)",
    "zh_Hant-native": "中文（繁體）",
    "zh_Hant_HK-formal": "Chinese (Traditional, Hong Kong SAR China)",
    "zh_Hant_HK-native": "中文（繁體字，中國香港特別行政區）",
    "zh_Hant_MO-formal": "Chinese (Traditional, Macau SAR China)",
    "zh_Hant_MO-native": "中文（繁體字，中國澳門特別行政區）",
    "zh_Hant_TW-formal": "Chinese (Traditional, Taiwan)",
    "zh_Hant_TW-native": "中文（繁體，台灣）",
    "zu-formal": "Zulu",
    "zu-native": "isiZulu",
    "zu_ZA-formal": "Zulu (South Africa)",
    "zu_ZA-native": "isiZulu (iNingizimu Afrika)",
};
