var describrtz = {
    Africa: [
        { value: "Africa/Abidjan", display: "Africa/Abidjan" },
        { value: "Africa/Accra", display: "Africa/Accra" },
        { value: "Africa/Addis_Ababa", display: "Africa/Addis Ababa" },
        { value: "Africa/Algiers", display: "Africa/Algiers" },
        { value: "Africa/Asmara", display: "Africa/Asmara" },
        { value: "Africa/Bamako", display: "Africa/Bamako" },
        { value: "Africa/Bangui", display: "Africa/Bangui" },
        { value: "Africa/Banjul", display: "Africa/Banjul" },
        { value: "Africa/Bissau", display: "Africa/Bissau" },
        { value: "Africa/Blantyre", display: "Africa/Blantyre" },
        { value: "Africa/Brazzaville", display: "Africa/Brazzaville" },
        { value: "Africa/Bujumbura", display: "Africa/Bujumbura" },
        { value: "Africa/Cairo", display: "Africa/Cairo" },
        { value: "Africa/Casablanca", display: "Africa/Casablanca" },
        { value: "Africa/Ceuta", display: "Africa/Ceuta" },
        { value: "Africa/Conakry", display: "Africa/Conakry" },
        { value: "Africa/Dakar", display: "Africa/Dakar" },
        { value: "Africa/Dar_es_Salaam", display: "Africa/Dar es Salaam" },
        { value: "Africa/Djibouti", display: "Africa/Djibouti" },
        { value: "Africa/Douala", display: "Africa/Douala" },
        { value: "Africa/El_Aaiun", display: "Africa/El Aaiun" },
        { value: "Africa/Freetown", display: "Africa/Freetown" },
        { value: "Africa/Gaborone", display: "Africa/Gaborone" },
        { value: "Africa/Harare", display: "Africa/Harare" },
        { value: "Africa/Johannesburg", display: "Africa/Johannesburg" },
        { value: "Africa/Juba", display: "Africa/Juba" },
        { value: "Africa/Kampala", display: "Africa/Kampala" },
        { value: "Africa/Khartoum", display: "Africa/Khartoum" },
        { value: "Africa/Kigali", display: "Africa/Kigali" },
        { value: "Africa/Kinshasa", display: "Africa/Kinshasa" },
        { value: "Africa/Lagos", display: "Africa/Lagos" },
        { value: "Africa/Libreville", display: "Africa/Libreville" },
        { value: "Africa/Lome", display: "Africa/Lome" },
        { value: "Africa/Luanda", display: "Africa/Luanda" },
        { value: "Africa/Lubumbashi", display: "Africa/Lubumbashi" },
        { value: "Africa/Lusaka", display: "Africa/Lusaka" },
        { value: "Africa/Malabo", display: "Africa/Malabo" },
        { value: "Africa/Maputo", display: "Africa/Maputo" },
        { value: "Africa/Maseru", display: "Africa/Maseru" },
        { value: "Africa/Mbabane", display: "Africa/Mbabane" },
        { value: "Africa/Mogadishu", display: "Africa/Mogadishu" },
        { value: "Africa/Monrovia", display: "Africa/Monrovia" },
        { value: "Africa/Nairobi", display: "Africa/Nairobi" },
        { value: "Africa/Ndjamena", display: "Africa/Ndjamena" },
        { value: "Africa/Niamey", display: "Africa/Niamey" },
        { value: "Africa/Nouakchott", display: "Africa/Nouakchott" },
        { value: "Africa/Ouagadougou", display: "Africa/Ouagadougou" },
        { value: "Africa/Porto-Novo", display: "Africa/Porto-Novo" },
        { value: "Africa/Sao_Tome", display: "Africa/Sao Tome" },
        { value: "Africa/Tripoli", display: "Africa/Tripoli" },
        { value: "Africa/Tunis", display: "Africa/Tunis" },
        { value: "Africa/Windhoek", display: "Africa/Windhoek" },
    ],
    America: [
        { value: "America/Adak", display: "America/Adak" },
        { value: "America/Anchorage", display: "America/Anchorage" },
        { value: "America/Anguilla", display: "America/Anguilla" },
        { value: "America/Antigua", display: "America/Antigua" },
        { value: "America/Araguaina", display: "America/Araguaina" },
        { value: "America/Argentina/Buenos_Aires", display: "America/Argentina/Buenos Aires" },
        { value: "America/Argentina/Catamarca", display: "America/Argentina/Catamarca" },
        { value: "America/Argentina/Cordoba", display: "America/Argentina/Cordoba" },
        { value: "America/Argentina/Jujuy", display: "America/Argentina/Jujuy" },
        { value: "America/Argentina/La_Rioja", display: "America/Argentina/La Rioja" },
        { value: "America/Argentina/Mendoza", display: "America/Argentina/Mendoza" },
        { value: "America/Argentina/Rio_Gallegos", display: "America/Argentina/Rio Gallegos" },
        { value: "America/Argentina/Salta", display: "America/Argentina/Salta" },
        { value: "America/Argentina/San_Juan", display: "America/Argentina/San Juan" },
        { value: "America/Argentina/San_Luis", display: "America/Argentina/San Luis" },
        { value: "America/Argentina/Tucuman", display: "America/Argentina/Tucuman" },
        { value: "America/Argentina/Ushuaia", display: "America/Argentina/Ushuaia" },
        { value: "America/Aruba", display: "America/Aruba" },
        { value: "America/Asuncion", display: "America/Asuncion" },
        { value: "America/Atikokan", display: "America/Atikokan" },
        { value: "America/Bahia", display: "America/Bahia" },
        { value: "America/Bahia_Banderas", display: "America/Bahia Banderas" },
        { value: "America/Barbados", display: "America/Barbados" },
        { value: "America/Belem", display: "America/Belem" },
        { value: "America/Belize", display: "America/Belize" },
        { value: "America/Blanc-Sablon", display: "America/Blanc-Sablon" },
        { value: "America/Boa_Vista", display: "America/Boa Vista" },
        { value: "America/Bogota", display: "America/Bogota" },
        { value: "America/Boise", display: "America/Boise" },
        { value: "America/Cambridge_Bay", display: "America/Cambridge Bay" },
        { value: "America/Campo_Grande", display: "America/Campo Grande" },
        { value: "America/Cancun", display: "America/Cancun" },
        { value: "America/Caracas", display: "America/Caracas" },
        { value: "America/Cayenne", display: "America/Cayenne" },
        { value: "America/Cayman", display: "America/Cayman" },
        { value: "America/Chicago", display: "America/Chicago" },
        { value: "America/Chihuahua", display: "America/Chihuahua" },
        { value: "America/Costa_Rica", display: "America/Costa Rica" },
        { value: "America/Creston", display: "America/Creston" },
        { value: "America/Cuiaba", display: "America/Cuiaba" },
        { value: "America/Curacao", display: "America/Curacao" },
        { value: "America/Danmarkshavn", display: "America/Danmarkshavn" },
        { value: "America/Dawson", display: "America/Dawson" },
        { value: "America/Dawson_Creek", display: "America/Dawson Creek" },
        { value: "America/Denver", display: "America/Denver" },
        { value: "America/Detroit", display: "America/Detroit" },
        { value: "America/Dominica", display: "America/Dominica" },
        { value: "America/Edmonton", display: "America/Edmonton" },
        { value: "America/Eirunepe", display: "America/Eirunepe" },
        { value: "America/El_Salvador", display: "America/El Salvador" },
        { value: "America/Fortaleza", display: "America/Fortaleza" },
        { value: "America/Fort_Nelson", display: "America/Fort Nelson" },
        { value: "America/Glace_Bay", display: "America/Glace Bay" },
        { value: "America/Goose_Bay", display: "America/Goose Bay" },
        { value: "America/Grand_Turk", display: "America/Grand Turk" },
        { value: "America/Grenada", display: "America/Grenada" },
        { value: "America/Guadeloupe", display: "America/Guadeloupe" },
        { value: "America/Guatemala", display: "America/Guatemala" },
        { value: "America/Guayaquil", display: "America/Guayaquil" },
        { value: "America/Guyana", display: "America/Guyana" },
        { value: "America/Halifax", display: "America/Halifax" },
        { value: "America/Havana", display: "America/Havana" },
        { value: "America/Hermosillo", display: "America/Hermosillo" },
        { value: "America/Indiana/Indianapolis", display: "America/Indiana/Indianapolis" },
        { value: "America/Indiana/Knox", display: "America/Indiana/Knox" },
        { value: "America/Indiana/Marengo", display: "America/Indiana/Marengo" },
        { value: "America/Indiana/Petersburg", display: "America/Indiana/Petersburg" },
        { value: "America/Indiana/Tell_City", display: "America/Indiana/Tell City" },
        { value: "America/Indiana/Vevay", display: "America/Indiana/Vevay" },
        { value: "America/Indiana/Vincennes", display: "America/Indiana/Vincennes" },
        { value: "America/Indiana/Winamac", display: "America/Indiana/Winamac" },
        { value: "America/Inuvik", display: "America/Inuvik" },
        { value: "America/Iqaluit", display: "America/Iqaluit" },
        { value: "America/Jamaica", display: "America/Jamaica" },
        { value: "America/Juneau", display: "America/Juneau" },
        { value: "America/Kentucky/Louisville", display: "America/Kentucky/Louisville" },
        { value: "America/Kentucky/Monticello", display: "America/Kentucky/Monticello" },
        { value: "America/Kralendijk", display: "America/Kralendijk" },
        { value: "America/La_Paz", display: "America/La Paz" },
        { value: "America/Lima", display: "America/Lima" },
        { value: "America/Los_Angeles", display: "America/Los Angeles" },
        { value: "America/Lower_Princes", display: "America/Lower Princes" },
        { value: "America/Maceio", display: "America/Maceio" },
        { value: "America/Managua", display: "America/Managua" },
        { value: "America/Manaus", display: "America/Manaus" },
        { value: "America/Marigot", display: "America/Marigot" },
        { value: "America/Martinique", display: "America/Martinique" },
        { value: "America/Matamoros", display: "America/Matamoros" },
        { value: "America/Mazatlan", display: "America/Mazatlan" },
        { value: "America/Menominee", display: "America/Menominee" },
        { value: "America/Merida", display: "America/Merida" },
        { value: "America/Metlakatla", display: "America/Metlakatla" },
        { value: "America/Mexico_City", display: "America/Mexico City" },
        { value: "America/Miquelon", display: "America/Miquelon" },
        { value: "America/Moncton", display: "America/Moncton" },
        { value: "America/Monterrey", display: "America/Monterrey" },
        { value: "America/Montevideo", display: "America/Montevideo" },
        { value: "America/Montserrat", display: "America/Montserrat" },
        { value: "America/Nassau", display: "America/Nassau" },
        { value: "America/New_York", display: "America/New York" },
        { value: "America/Nipigon", display: "America/Nipigon" },
        { value: "America/Nome", display: "America/Nome" },
        { value: "America/Noronha", display: "America/Noronha" },
        { value: "America/North_Dakota/Beulah", display: "America/North Dakota/Beulah" },
        { value: "America/North_Dakota/Center", display: "America/North Dakota/Center" },
        { value: "America/North_Dakota/New_Salem", display: "America/North Dakota/New Salem" },
        { value: "America/Nuuk", display: "America/Nuuk" },
        { value: "America/Ojinaga", display: "America/Ojinaga" },
        { value: "America/Panama", display: "America/Panama" },
        { value: "America/Pangnirtung", display: "America/Pangnirtung" },
        { value: "America/Paramaribo", display: "America/Paramaribo" },
        { value: "America/Phoenix", display: "America/Phoenix" },
        { value: "America/Port-au-Prince", display: "America/Port-au-Prince" },
        { value: "America/Port_of_Spain", display: "America/Port of Spain" },
        { value: "America/Porto_Velho", display: "America/Porto Velho" },
        { value: "America/Puerto_Rico", display: "America/Puerto Rico" },
        { value: "America/Punta_Arenas", display: "America/Punta Arenas" },
        { value: "America/Rainy_River", display: "America/Rainy River" },
        { value: "America/Rankin_Inlet", display: "America/Rankin Inlet" },
        { value: "America/Recife", display: "America/Recife" },
        { value: "America/Regina", display: "America/Regina" },
        { value: "America/Resolute", display: "America/Resolute" },
        { value: "America/Rio_Branco", display: "America/Rio Branco" },
        { value: "America/Santarem", display: "America/Santarem" },
        { value: "America/Santiago", display: "America/Santiago" },
        { value: "America/Santo_Domingo", display: "America/Santo Domingo" },
        { value: "America/Sao_Paulo", display: "America/Sao Paulo" },
        { value: "America/Scoresbysund", display: "America/Scoresbysund" },
        { value: "America/Sitka", display: "America/Sitka" },
        { value: "America/St_Barthelemy", display: "America/St Barthelemy" },
        { value: "America/St_Johns", display: "America/St Johns" },
        { value: "America/St_Kitts", display: "America/St Kitts" },
        { value: "America/St_Lucia", display: "America/St Lucia" },
        { value: "America/St_Thomas", display: "America/St Thomas" },
        { value: "America/St_Vincent", display: "America/St Vincent" },
        { value: "America/Swift_Current", display: "America/Swift Current" },
        { value: "America/Tegucigalpa", display: "America/Tegucigalpa" },
        { value: "America/Thule", display: "America/Thule" },
        { value: "America/Thunder_Bay", display: "America/Thunder Bay" },
        { value: "America/Tijuana", display: "America/Tijuana" },
        { value: "America/Toronto", display: "America/Toronto" },
        { value: "America/Tortola", display: "America/Tortola" },
        { value: "America/Vancouver", display: "America/Vancouver" },
        { value: "America/Whitehorse", display: "America/Whitehorse" },
        { value: "America/Winnipeg", display: "America/Winnipeg" },
        { value: "America/Yakutat", display: "America/Yakutat" },
        { value: "America/Yellowknife", display: "America/Yellowknife" },
    ],
    Antarctica: [
        { value: "Antarctica/Casey", display: "Antarctica/Casey" },
        { value: "Antarctica/Davis", display: "Antarctica/Davis" },
        { value: "Antarctica/DumontDUrville", display: "Antarctica/DumontDUrville" },
        { value: "Antarctica/Macquarie", display: "Antarctica/Macquarie" },
        { value: "Antarctica/Mawson", display: "Antarctica/Mawson" },
        { value: "Antarctica/McMurdo", display: "Antarctica/McMurdo" },
        { value: "Antarctica/Palmer", display: "Antarctica/Palmer" },
        { value: "Antarctica/Rothera", display: "Antarctica/Rothera" },
        { value: "Antarctica/Syowa", display: "Antarctica/Syowa" },
        { value: "Antarctica/Troll", display: "Antarctica/Troll" },
        { value: "Antarctica/Vostok", display: "Antarctica/Vostok" },
    ],
    Arctic: [{ value: "Arctic/Longyearbyen", display: "Arctic/Longyearbyen" }],
    Asia: [
        { value: "Asia/Aden", display: "Asia/Aden" },
        { value: "Asia/Almaty", display: "Asia/Almaty" },
        { value: "Asia/Amman", display: "Asia/Amman" },
        { value: "Asia/Anadyr", display: "Asia/Anadyr" },
        { value: "Asia/Aqtau", display: "Asia/Aqtau" },
        { value: "Asia/Aqtobe", display: "Asia/Aqtobe" },
        { value: "Asia/Ashgabat", display: "Asia/Ashgabat" },
        { value: "Asia/Atyrau", display: "Asia/Atyrau" },
        { value: "Asia/Baghdad", display: "Asia/Baghdad" },
        { value: "Asia/Bahrain", display: "Asia/Bahrain" },
        { value: "Asia/Baku", display: "Asia/Baku" },
        { value: "Asia/Bangkok", display: "Asia/Bangkok" },
        { value: "Asia/Barnaul", display: "Asia/Barnaul" },
        { value: "Asia/Beirut", display: "Asia/Beirut" },
        { value: "Asia/Bishkek", display: "Asia/Bishkek" },
        { value: "Asia/Brunei", display: "Asia/Brunei" },
        { value: "Asia/Chita", display: "Asia/Chita" },
        { value: "Asia/Choibalsan", display: "Asia/Choibalsan" },
        { value: "Asia/Colombo", display: "Asia/Colombo" },
        { value: "Asia/Damascus", display: "Asia/Damascus" },
        { value: "Asia/Dhaka", display: "Asia/Dhaka" },
        { value: "Asia/Dili", display: "Asia/Dili" },
        { value: "Asia/Dubai", display: "Asia/Dubai" },
        { value: "Asia/Dushanbe", display: "Asia/Dushanbe" },
        { value: "Asia/Famagusta", display: "Asia/Famagusta" },
        { value: "Asia/Gaza", display: "Asia/Gaza" },
        { value: "Asia/Hebron", display: "Asia/Hebron" },
        { value: "Asia/Ho_Chi_Minh", display: "Asia/Ho Chi Minh" },
        { value: "Asia/Hong_Kong", display: "Asia/Hong Kong" },
        { value: "Asia/Hovd", display: "Asia/Hovd" },
        { value: "Asia/Irkutsk", display: "Asia/Irkutsk" },
        { value: "Asia/Jakarta", display: "Asia/Jakarta" },
        { value: "Asia/Jayapura", display: "Asia/Jayapura" },
        { value: "Asia/Jerusalem", display: "Asia/Jerusalem" },
        { value: "Asia/Kabul", display: "Asia/Kabul" },
        { value: "Asia/Kamchatka", display: "Asia/Kamchatka" },
        { value: "Asia/Karachi", display: "Asia/Karachi" },
        { value: "Asia/Kathmandu", display: "Asia/Kathmandu" },
        { value: "Asia/Khandyga", display: "Asia/Khandyga" },
        { value: "Asia/Kolkata", display: "Asia/Kolkata" },
        { value: "Asia/Krasnoyarsk", display: "Asia/Krasnoyarsk" },
        { value: "Asia/Kuala_Lumpur", display: "Asia/Kuala Lumpur" },
        { value: "Asia/Kuching", display: "Asia/Kuching" },
        { value: "Asia/Kuwait", display: "Asia/Kuwait" },
        { value: "Asia/Macau", display: "Asia/Macau" },
        { value: "Asia/Magadan", display: "Asia/Magadan" },
        { value: "Asia/Makassar", display: "Asia/Makassar" },
        { value: "Asia/Manila", display: "Asia/Manila" },
        { value: "Asia/Muscat", display: "Asia/Muscat" },
        { value: "Asia/Nicosia", display: "Asia/Nicosia" },
        { value: "Asia/Novokuznetsk", display: "Asia/Novokuznetsk" },
        { value: "Asia/Novosibirsk", display: "Asia/Novosibirsk" },
        { value: "Asia/Omsk", display: "Asia/Omsk" },
        { value: "Asia/Oral", display: "Asia/Oral" },
        { value: "Asia/Phnom_Penh", display: "Asia/Phnom Penh" },
        { value: "Asia/Pontianak", display: "Asia/Pontianak" },
        { value: "Asia/Pyongyang", display: "Asia/Pyongyang" },
        { value: "Asia/Qatar", display: "Asia/Qatar" },
        { value: "Asia/Qostanay", display: "Asia/Qostanay" },
        { value: "Asia/Qyzylorda", display: "Asia/Qyzylorda" },
        { value: "Asia/Riyadh", display: "Asia/Riyadh" },
        { value: "Asia/Sakhalin", display: "Asia/Sakhalin" },
        { value: "Asia/Samarkand", display: "Asia/Samarkand" },
        { value: "Asia/Seoul", display: "Asia/Seoul" },
        { value: "Asia/Shanghai", display: "Asia/Shanghai" },
        { value: "Asia/Singapore", display: "Asia/Singapore" },
        { value: "Asia/Srednekolymsk", display: "Asia/Srednekolymsk" },
        { value: "Asia/Taipei", display: "Asia/Taipei" },
        { value: "Asia/Tashkent", display: "Asia/Tashkent" },
        { value: "Asia/Tbilisi", display: "Asia/Tbilisi" },
        { value: "Asia/Tehran", display: "Asia/Tehran" },
        { value: "Asia/Thimphu", display: "Asia/Thimphu" },
        { value: "Asia/Tokyo", display: "Asia/Tokyo" },
        { value: "Asia/Tomsk", display: "Asia/Tomsk" },
        { value: "Asia/Ulaanbaatar", display: "Asia/Ulaanbaatar" },
        { value: "Asia/Urumqi", display: "Asia/Urumqi" },
        { value: "Asia/Ust-Nera", display: "Asia/Ust-Nera" },
        { value: "Asia/Vientiane", display: "Asia/Vientiane" },
        { value: "Asia/Vladivostok", display: "Asia/Vladivostok" },
        { value: "Asia/Yakutsk", display: "Asia/Yakutsk" },
        { value: "Asia/Yangon", display: "Asia/Yangon" },
        { value: "Asia/Yekaterinburg", display: "Asia/Yekaterinburg" },
        { value: "Asia/Yerevan", display: "Asia/Yerevan" },
    ],
    Atlantic: [
        { value: "Atlantic/Azores", display: "Atlantic/Azores" },
        { value: "Atlantic/Bermuda", display: "Atlantic/Bermuda" },
        { value: "Atlantic/Canary", display: "Atlantic/Canary" },
        { value: "Atlantic/Cape_Verde", display: "Atlantic/Cape Verde" },
        { value: "Atlantic/Faroe", display: "Atlantic/Faroe" },
        { value: "Atlantic/Madeira", display: "Atlantic/Madeira" },
        { value: "Atlantic/Reykjavik", display: "Atlantic/Reykjavik" },
        { value: "Atlantic/South_Georgia", display: "Atlantic/South Georgia" },
        { value: "Atlantic/Stanley", display: "Atlantic/Stanley" },
        { value: "Atlantic/St_Helena", display: "Atlantic/St Helena" },
    ],
    Australia: [
        { value: "Australia/Adelaide", display: "Australia/Adelaide" },
        { value: "Australia/Brisbane", display: "Australia/Brisbane" },
        { value: "Australia/Broken_Hill", display: "Australia/Broken Hill" },
        { value: "Australia/Currie", display: "Australia/Currie" },
        { value: "Australia/Darwin", display: "Australia/Darwin" },
        { value: "Australia/Eucla", display: "Australia/Eucla" },
        { value: "Australia/Hobart", display: "Australia/Hobart" },
        { value: "Australia/Lindeman", display: "Australia/Lindeman" },
        { value: "Australia/Lord_Howe", display: "Australia/Lord Howe" },
        { value: "Australia/Melbourne", display: "Australia/Melbourne" },
        { value: "Australia/Perth", display: "Australia/Perth" },
        { value: "Australia/Sydney", display: "Australia/Sydney" },
    ],
    Europe: [
        { value: "Europe/Amsterdam", display: "Europe/Amsterdam" },
        { value: "Europe/Andorra", display: "Europe/Andorra" },
        { value: "Europe/Astrakhan", display: "Europe/Astrakhan" },
        { value: "Europe/Athens", display: "Europe/Athens" },
        { value: "Europe/Belgrade", display: "Europe/Belgrade" },
        { value: "Europe/Berlin", display: "Europe/Berlin" },
        { value: "Europe/Bratislava", display: "Europe/Bratislava" },
        { value: "Europe/Brussels", display: "Europe/Brussels" },
        { value: "Europe/Bucharest", display: "Europe/Bucharest" },
        { value: "Europe/Budapest", display: "Europe/Budapest" },
        { value: "Europe/Busingen", display: "Europe/Busingen" },
        { value: "Europe/Chisinau", display: "Europe/Chisinau" },
        { value: "Europe/Copenhagen", display: "Europe/Copenhagen" },
        { value: "Europe/Dublin", display: "Europe/Dublin" },
        { value: "Europe/Gibraltar", display: "Europe/Gibraltar" },
        { value: "Europe/Guernsey", display: "Europe/Guernsey" },
        { value: "Europe/Helsinki", display: "Europe/Helsinki" },
        { value: "Europe/Isle_of_Man", display: "Europe/Isle of Man" },
        { value: "Europe/Istanbul", display: "Europe/Istanbul" },
        { value: "Europe/Jersey", display: "Europe/Jersey" },
        { value: "Europe/Kaliningrad", display: "Europe/Kaliningrad" },
        { value: "Europe/Kiev", display: "Europe/Kiev" },
        { value: "Europe/Kirov", display: "Europe/Kirov" },
        { value: "Europe/Lisbon", display: "Europe/Lisbon" },
        { value: "Europe/Ljubljana", display: "Europe/Ljubljana" },
        { value: "Europe/London", display: "Europe/London" },
        { value: "Europe/Luxembourg", display: "Europe/Luxembourg" },
        { value: "Europe/Madrid", display: "Europe/Madrid" },
        { value: "Europe/Malta", display: "Europe/Malta" },
        { value: "Europe/Mariehamn", display: "Europe/Mariehamn" },
        { value: "Europe/Minsk", display: "Europe/Minsk" },
        { value: "Europe/Monaco", display: "Europe/Monaco" },
        { value: "Europe/Moscow", display: "Europe/Moscow" },
        { value: "Europe/Oslo", display: "Europe/Oslo" },
        { value: "Europe/Paris", display: "Europe/Paris" },
        { value: "Europe/Podgorica", display: "Europe/Podgorica" },
        { value: "Europe/Prague", display: "Europe/Prague" },
        { value: "Europe/Riga", display: "Europe/Riga" },
        { value: "Europe/Rome", display: "Europe/Rome" },
        { value: "Europe/Samara", display: "Europe/Samara" },
        { value: "Europe/San_Marino", display: "Europe/San Marino" },
        { value: "Europe/Sarajevo", display: "Europe/Sarajevo" },
        { value: "Europe/Saratov", display: "Europe/Saratov" },
        { value: "Europe/Simferopol", display: "Europe/Simferopol" },
        { value: "Europe/Skopje", display: "Europe/Skopje" },
        { value: "Europe/Sofia", display: "Europe/Sofia" },
        { value: "Europe/Stockholm", display: "Europe/Stockholm" },
        { value: "Europe/Tallinn", display: "Europe/Tallinn" },
        { value: "Europe/Tirane", display: "Europe/Tirane" },
        { value: "Europe/Ulyanovsk", display: "Europe/Ulyanovsk" },
        { value: "Europe/Uzhgorod", display: "Europe/Uzhgorod" },
        { value: "Europe/Vaduz", display: "Europe/Vaduz" },
        { value: "Europe/Vatican", display: "Europe/Vatican" },
        { value: "Europe/Vienna", display: "Europe/Vienna" },
        { value: "Europe/Vilnius", display: "Europe/Vilnius" },
        { value: "Europe/Volgograd", display: "Europe/Volgograd" },
        { value: "Europe/Warsaw", display: "Europe/Warsaw" },
        { value: "Europe/Zagreb", display: "Europe/Zagreb" },
        { value: "Europe/Zaporozhye", display: "Europe/Zaporozhye" },
        { value: "Europe/Zurich", display: "Europe/Zurich" },
    ],
    Indian: [
        { value: "Indian/Antananarivo", display: "Indian/Antananarivo" },
        { value: "Indian/Chagos", display: "Indian/Chagos" },
        { value: "Indian/Christmas", display: "Indian/Christmas" },
        { value: "Indian/Cocos", display: "Indian/Cocos" },
        { value: "Indian/Comoro", display: "Indian/Comoro" },
        { value: "Indian/Kerguelen", display: "Indian/Kerguelen" },
        { value: "Indian/Mahe", display: "Indian/Mahe" },
        { value: "Indian/Maldives", display: "Indian/Maldives" },
        { value: "Indian/Mauritius", display: "Indian/Mauritius" },
        { value: "Indian/Mayotte", display: "Indian/Mayotte" },
        { value: "Indian/Reunion", display: "Indian/Reunion" },
    ],
    Pacific: [
        { value: "Pacific/Apia", display: "Pacific/Apia" },
        { value: "Pacific/Auckland", display: "Pacific/Auckland" },
        { value: "Pacific/Bougainville", display: "Pacific/Bougainville" },
        { value: "Pacific/Chatham", display: "Pacific/Chatham" },
        { value: "Pacific/Chuuk", display: "Pacific/Chuuk" },
        { value: "Pacific/Easter", display: "Pacific/Easter" },
        { value: "Pacific/Efate", display: "Pacific/Efate" },
        { value: "Pacific/Enderbury", display: "Pacific/Enderbury" },
        { value: "Pacific/Fakaofo", display: "Pacific/Fakaofo" },
        { value: "Pacific/Fiji", display: "Pacific/Fiji" },
        { value: "Pacific/Funafuti", display: "Pacific/Funafuti" },
        { value: "Pacific/Galapagos", display: "Pacific/Galapagos" },
        { value: "Pacific/Gambier", display: "Pacific/Gambier" },
        { value: "Pacific/Guadalcanal", display: "Pacific/Guadalcanal" },
        { value: "Pacific/Guam", display: "Pacific/Guam" },
        { value: "Pacific/Honolulu", display: "Pacific/Honolulu" },
        { value: "Pacific/Kiritimati", display: "Pacific/Kiritimati" },
        { value: "Pacific/Kosrae", display: "Pacific/Kosrae" },
        { value: "Pacific/Kwajalein", display: "Pacific/Kwajalein" },
        { value: "Pacific/Majuro", display: "Pacific/Majuro" },
        { value: "Pacific/Marquesas", display: "Pacific/Marquesas" },
        { value: "Pacific/Midway", display: "Pacific/Midway" },
        { value: "Pacific/Nauru", display: "Pacific/Nauru" },
        { value: "Pacific/Niue", display: "Pacific/Niue" },
        { value: "Pacific/Norfolk", display: "Pacific/Norfolk" },
        { value: "Pacific/Noumea", display: "Pacific/Noumea" },
        { value: "Pacific/Pago_Pago", display: "Pacific/Pago Pago" },
        { value: "Pacific/Palau", display: "Pacific/Palau" },
        { value: "Pacific/Pitcairn", display: "Pacific/Pitcairn" },
        { value: "Pacific/Pohnpei", display: "Pacific/Pohnpei" },
        { value: "Pacific/Port_Moresby", display: "Pacific/Port Moresby" },
        { value: "Pacific/Rarotonga", display: "Pacific/Rarotonga" },
        { value: "Pacific/Saipan", display: "Pacific/Saipan" },
        { value: "Pacific/Tahiti", display: "Pacific/Tahiti" },
        { value: "Pacific/Tarawa", display: "Pacific/Tarawa" },
        { value: "Pacific/Tongatapu", display: "Pacific/Tongatapu" },
        { value: "Pacific/Wake", display: "Pacific/Wake" },
        { value: "Pacific/Wallis", display: "Pacific/Wallis" },
    ],
    Manual_Offsets: [
        { value: "-12", display: "UTC-12:00" },
        { value: "-11.5", display: "UTC-11:30" },
        { value: "-11", display: "UTC-11:00" },
        { value: "-10.5", display: "UTC-10:30" },
        { value: "-10", display: "UTC-10:00" },
        { value: "-9.5", display: "UTC-09:30" },
        { value: "-9", display: "UTC-09:00" },
        { value: "-8.5", display: "UTC-08:30" },
        { value: "-8", display: "UTC-08:00" },
        { value: "-7.5", display: "UTC-07:30" },
        { value: "-7", display: "UTC-07:00" },
        { value: "-6.5", display: "UTC-06:30" },
        { value: "-6", display: "UTC-06:00" },
        { value: "-5.5", display: "UTC-05:30" },
        { value: "-5", display: "UTC-05:00" },
        { value: "-4.5", display: "UTC-04:30" },
        { value: "-4", display: "UTC-04:00" },
        { value: "-3.5", display: "UTC-03:30" },
        { value: "-3", display: "UTC-03:00" },
        { value: "-2.5", display: "UTC-02:30" },
        { value: "-2", display: "UTC-02:00" },
        { value: "-1.5", display: "UTC-01:30" },
        { value: "-1", display: "UTC-01:00" },
        { value: "-0.5", display: "UTC-00:30" },
        { value: "+0", display: "UTC+00:00" },
        { value: "+0.5", display: "UTC+00:30" },
        { value: "+1", display: "UTC+01:00" },
        { value: "+1.5", display: "UTC+01:30" },
        { value: "+2", display: "UTC+02:00" },
        { value: "+2.5", display: "UTC+02:30" },
        { value: "+3", display: "UTC+03:00" },
        { value: "+3.5", display: "UTC+03:30" },
        { value: "+4", display: "UTC+04:00" },
        { value: "+4.5", display: "UTC+04:30" },
        { value: "+5", display: "UTC+05:00" },
        { value: "+5.5", display: "UTC+05:30" },
        { value: "+5.75", display: "UTC+05:45" },
        { value: "+6", display: "UTC+06:00" },
        { value: "+6.5", display: "UTC+06:30" },
        { value: "+7", display: "UTC+07:00" },
        { value: "+7.5", display: "UTC+07:30" },
        { value: "+8", display: "UTC+08:00" },
        { value: "+8.5", display: "UTC+08:30" },
        { value: "+8.75", display: "UTC+08:45" },
        { value: "+9", display: "UTC+09:00" },
        { value: "+9.5", display: "UTC+09:30" },
        { value: "+10", display: "UTC+10:00" },
        { value: "+10.5", display: "UTC+10:30" },
        { value: "+11", display: "UTC+11:00" },
        { value: "+11.5", display: "UTC+11:30" },
        { value: "+12", display: "UTC+12:00" },
        { value: "+12.75", display: "UTC+12:45" },
        { value: "+13", display: "UTC+13:00" },
        { value: "+13.75", display: "UTC+13:45" },
        { value: "+14", display: "UTC+14:00" },
    ],
};
